version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: PostgresDB
    environment:
      POSTGRES_DB: auctions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

  app:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auctions
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    depends_on:
      - db

volumes:
  postgres-data:
