CREATE TABLE IF NOT EXISTS recovery_tokens (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email VARCHAR(100),
    token VARCHAR(100),
    expiration BIGINT,
    user_id INT,
    FOREIGN KEY(user_id) REFERENCES users(id)
)